version: '3.2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  redis:
    image: redis:alpine
    restart: always
    networks:
      - redisnet
    expose:
      - 6379
    environment:
      - REDIS_HOST_PASSWORD_FILE=/run/secrets/redis_host_password
    secrets:
      - redis_host_password
  
  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nc_data:/var/www/html
    networks:
      - redisnet
      - dbnet
    environment:
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD_FILE=/run/secrets/redis_host_password
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    depends_on:
      - db
      - redis
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

volumes:
  db_data:
  nc_data:

networks:
  dbnet:
  redisnet:

secrets:
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.txt 
  nextcloud_admin_user:
    file: ./nextcloud_admin_user.txt 
  postgres_db:
    file: ./postgres_db.txt 
  postgres_password:
    file: ./postgres_password.txt 
  postgres_user:
    file: ./postgres_user.txt 
  redis_host_password:
    file: ./redis_host_password.txt