version: '3.2'
services:
  nc:
    image: nextcloud:apache
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
    ports:
      - 8088:80
    restart: always
    volumes:
      - nc_data:/var/www/html
    depends_on:
      - db
      - redis
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
volumes:
  db_data:
  nc_data: